version: '3.1'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html 
    ports:
      - 127.0.0.1:9000:80
  db:
    image: mysql:8.0.28-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: xsscsrfdemo
    volumes:
      - ./db:/docker-entrypoint-initdb.d 
    ports:
      - 127.0.0.1:3306:3306

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 127.0.0.1:8082:8080